In [14]:
%matplotlib inline
from keras.utils.vis_utils import plot_model
from keras.models import Model,Sequential
from tensorflow.keras.utils import to_categorical
from keras.layers import Input, Dense, Dropout
from tensorflow.keras.optimizers import SGD, Adam
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [15]:
data = pd.read_csv("dataset.csv")
data.head()

battery_power  blue  clock_speed  ...  touch_screen  wifi  price_range
0            842     0          2.2  ...             0     1            1
1           1021     1          0.5  ...             1     0            2
2            563     1          0.5  ...             1     0            2
3            615     1          2.5  ...             0     0            2
4           1821     1          1.2  ...             1     0            1

[5 rows x 21 columns]

In [16]:
print(data.shape)
train=[]
for i in range(data.shape[0]):
  train.append(list(data.iloc[i]))

(2000, 21)


In [17]:
x=[]
y=[]
for i in train:
  y.append(i[-1])
  x.append(i[:20])
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=29)


In [18]:
x_train = np.array(x_train)
y_train = np.array(y_train)
x_test = np.array(x_test)
y_test = np.array(y_test)
print(x_train)
print(y_train)

[[1.412e+03 1.000e+00 2.400e+00 ... 0.000e+00 0.000e+00 1.000e+00]
 [8.080e+02 1.000e+00 5.000e-01 ... 1.000e+00 0.000e+00 1.000e+00]
 [1.619e+03 1.000e+00 9.000e-01 ... 1.000e+00 0.000e+00 1.000e+00]
 ...
 [1.872e+03 1.000e+00 2.300e+00 ... 1.000e+00 0.000e+00 1.000e+00]
 [1.133e+03 0.000e+00 1.400e+00 ... 1.000e+00 0.000e+00 1.000e+00]
 [1.242e+03 1.000e+00 2.400e+00 ... 1.000e+00 0.000e+00 0.000e+00]]
[1. 0. 0. ... 2. 1. 0.]


In [19]:
y_train = to_categorical(y_train, 4)
y_test = to_categorical(y_test, 4)
print(y_test)

[[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 ...
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [21]:
model = Sequential()
model.add(Dense(300, input_dim=x_train.shape[1], activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(200, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(150, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(50, activation='relu'))
### YOU HAVE TO MAKE YOUR CHANGES HERE !!!
model.add(Dense(4, activation='softmax')) # softmax activation for last layer

opt = SGD(learning_rate=0.0001)
model.compile(loss='categorical_crossentropy', optimizer=opt, metrics=['accuracy'])

history = model.fit(x_train, y_train,
                    epochs=300,
                    batch_size=32,
                    verbose=1,
                    validation_data=(x_test,y_test))

# evaluate the keras model
_, accuracy = model.evaluate(x_train, y_train)
print('total train Accuracy: %.2f' % (accuracy*100))

_, accuracy2 = model.evaluate(x_test, y_test)
print('total validation Accuracy: %.2f' % (accuracy2*100))

Epoch 1/300
50/50 [==============================] - 1s 7ms/step - loss: 42.4334 - accuracy: 0.3675 - val_loss: 6.9914 - val_accuracy: 0.5150
Epoch 2/300
50/50 [==============================] - 0s 3ms/step - loss: 15.2425 - accuracy: 0.3744 - val_loss: 4.6020 - val_accuracy: 0.4175
Epoch 3/300
50/50 [==============================] - 0s 3ms/step - loss: 10.3632 - accuracy: 0.4019 - val_loss: 2.4370 - val_accuracy: 0.4075
Epoch 4/300
50/50 [==============================] - 0s 3ms/step - loss: 7.4679 - accuracy: 0.4194 - val_loss: 2.3569 - val_accuracy: 0.3900
Epoch 5/300
50/50 [==============================] - 0s 3ms/step - loss: 6.3169 - accuracy: 0.4031 - val_loss: 1.8055 - val_accuracy: 0.4475
Epoch 6/300
50/50 [==============================] - 0s 3ms/step - loss: 5.0914 - accuracy: 0.4081 - val_loss: 1.7350 - val_accuracy: 0.4100
Epoch 7/300
50/50 [==============================] - 0s 3ms/step - loss: 4.3237 - accuracy: 0.4288 - val_loss: 1.6345 - val_accuracy: 0.4225
Epoch 8/30